# Generated by Django 6.0.1 on 2026-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matricule',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
