# Generated by Django 6.0.1 on 2026-03-09 20:30

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_matricule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id_brigade', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code_brigade', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('annee_formation', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id_specialite', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code_classe', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.brigade')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date_depot', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publie'), ('ARCHIVE', 'Archive')], default='BROUILLON', max_length=30)),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='api.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id_controle', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('bareme', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publie'), ('CLOTURE', 'Cloture'), ('CORRIGE', 'Corrige')], default='BROUILLON', max_length=30)),
                ('enonce', models.TextField(blank=True, default='')),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles', to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='api.cours')),
            ],
        ),
        migrations.CreateModel(
            name='CoursFichier',
            fields=[
                ('id_cours_fichier', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('taille_octets', models.BigIntegerField(default=0)),
                ('contenu', models.BinaryField()),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='api.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lien_cible', models.CharField(blank=True, default='', max_length=500)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoumissionControle',
            fields=[
                ('id_soumission', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('fichier_reponse', models.BinaryField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('RETARD', 'Retard'), ('ANNULE', 'Annule')], default='SOUMIS', max_length=30)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='api.controle')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correction', models.TextField(blank=True, default='')),
                ('date_eval', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_publiee', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('soumission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='api.soumissioncontrole')),
            ],
        ),
        migrations.CreateModel(
            name='InstructeurProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_civil', models.BooleanField(default=False)),
                ('instructeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructeur_profil', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructeurs', to='api.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='StagiaireClasse',
            fields=[
                ('id_stagiaire_classe', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to='api.classe')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_stagiaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SujetFinStage',
            fields=[
                ('id_sujet', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('PROPOSE', 'Propose'), ('VALIDE', 'Valide'), ('ANNULE', 'Annule')], default='PROPOSE', max_length=30)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sujets_crees', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_fin_stage', to='api.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationSujetStage',
            fields=[
                ('id_affectation_sujet', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('ABANDONNE', 'Abandonne')], default='EN_COURS', max_length=30)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encadrements_sujet', to=settings.AUTH_USER_MODEL)),
                ('stagiaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sujet_fin_stage', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='api.sujetfinstage')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationInstructeurClasse',
            fields=[
                ('id_affectation', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_instructeur', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructeurs', to='api.classe')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='ck_affectation_classe_dates'), models.UniqueConstraint(fields=('instructeur', 'classe', 'date_debut'), name='uq_instructeur_classe_debut')],
            },
        ),
        migrations.CreateModel(
            name='ControleCorrection',
            fields=[
                ('id_correction', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('titre', models.CharField(blank=True, default='', max_length=255)),
                ('texte_correction', models.TextField(blank=True, default='')),
                ('fichier_correction', models.BinaryField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='api.controle')),
                ('publie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections_publiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('controle', 'version_no'), name='uq_controle_correction_version')],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id_inscription', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='ACTIVE', max_length=30)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.cours')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stagiaire', 'cours'), name='uq_stagiaire_cours')],
            },
        ),
        migrations.CreateModel(
            name='SessionCours',
            fields=[
                ('id_session', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('salle', models.CharField(blank=True, default='', max_length=100)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.cours')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='ck_session_dates')],
            },
        ),
        migrations.AddConstraint(
            model_name='soumissioncontrole',
            constraint=models.UniqueConstraint(fields=('controle', 'stagiaire'), name='uq_controle_stagiaire_soumission'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('note__gte', 0), ('note__lte', 20)), name='ck_note_0_20'),
        ),
        migrations.AddConstraint(
            model_name='stagiaireclasse',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='ck_stagiaire_classe_dates'),
        ),
    ]
