# Generated by Django 6.0.1 on 2026-03-09 22:45

import api.models
import django.db.models.deletion
from django.db import migrations, models


def seed_reference_tables(apps, schema_editor):
    Corps = apps.get_model("api", "Corps")
    Rank = apps.get_model("api", "Rank")
    Speciality = apps.get_model("api", "Speciality")
    UserProfile = apps.get_model("api", "UserProfile")

    corp_defaults = [
        ("ARMEE_TERRE", "Armee de Terre"),
        ("ARMEE_AIR", "Armee de l'Air"),
        ("MARINE", "Marine"),
        ("GENDARMERIE", "Gendarmerie"),
    ]
    created_corps = {}
    for code, label in corp_defaults:
        corps, _ = Corps.objects.get_or_create(code=code, defaults={"label": label})
        created_corps[code] = corps

    for code, label, corps_code in [
        ("CPL", "Caporal", "ARMEE_TERRE"),
        ("SGT", "Sergent", "ARMEE_TERRE"),
        ("LT", "Lieutenant", "ARMEE_AIR"),
        ("CNE", "Capitaine", "ARMEE_AIR"),
        ("ENS", "Enseigne", "MARINE"),
        ("LV", "Lieutenant de vaisseau", "MARINE"),
    ]:
        Rank.objects.get_or_create(code=code, defaults={"label": label, "corps": created_corps[corps_code]})

    for code, label in [
        ("INF", "Infanterie"),
        ("LOG", "Logistique"),
        ("COM", "Communication"),
        ("SYS", "Systemes d'information"),
        ("GEN", "General"),
    ]:
        Speciality.objects.get_or_create(code=code, defaults={"label": label})

    fallback_corps = created_corps["ARMEE_TERRE"]
    fallback_rank = Rank.objects.filter(corps=fallback_corps).order_by("label").first()
    fallback_speciality = Speciality.objects.filter(code="GEN").first()
    if fallback_rank and fallback_speciality:
        UserProfile.objects.filter(role="Instructeur", matricule="").update(est_civil=True)
        UserProfile.objects.exclude(role="Instructeur", est_civil=True).filter(corps__isnull=True).update(corps=fallback_corps)
        UserProfile.objects.exclude(role="Instructeur", est_civil=True).filter(rank__isnull=True).update(rank=fallback_rank)
        UserProfile.objects.exclude(role="Instructeur", est_civil=True).filter(speciality__isnull=True).update(
            speciality=fallback_speciality
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_brigade_specialite_classe_cours_controle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corps',
            fields=[
                ('id_corps', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id_speciality', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='est_civil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='corps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.corps'),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id_rank', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('corps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='api.corps')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.rank'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.speciality'),
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.UniqueConstraint(fields=('corps', 'label'), name='uq_rank_corps_label'),
        ),
        migrations.RunPython(seed_reference_tables, migrations.RunPython.noop),
    ]
