# Generated by Django 6.0.1 on 2026-03-09 22:54

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_corps_speciality_userprofile_est_civil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAudit',
            fields=[
                ('id_event', models.CharField(default=api.models.generate_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=32)),
                ('event_type', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=80)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
