# Generated by Django 6.0.1 on 2026-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bootstrap_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Instructeur', 'Instructeur'), ('Stagiaire', 'Stagiaire'), ('Admin', 'Admin'), ('Superviseur', 'Superviseur'), ('Coordinateur', 'Coordinateur')], default='Stagiaire', max_length=32),
        ),
    ]
