from django.urls import path

from .views import (
    AdminBulkCreateAccountsCsvView,
    AdminClassesView,
    AdminCorpsView,
    AdminCreateAccountView,
    AdminAssignInstructeurToClassView,
    AdminAssignStageaireToClassView,
    AdminDashboardView,
    AdminEventsView,
    AdminRanksView,
    AdminReferenceDataView,
    AdminSpecialitiesView,
    AdminSubjectCoursesView,
    AdminSubjectControlsView,
    AdminSubjectsView,
    AdminToggleUserStatusView,
    AdminUpdateCourseStatusView,
    AdminUpdateControlStatusView,
    CoordinateurDashboardView,
    HealthView,
    InstructeurDashboardView,
    InstructeurControleCreateView,
    InstructeurControleFichierView,
    InstructeurCoursCreateView,
    InstructeurCoursFichierView,
    InstructeurCoursFichierDownloadView,
    InstructeurEvaluateSoumissionView,
    InstructeurPublishCorrectionView,
    InstructeurSoumissionFichierView,
    MeView,
    PublicReferenceDataView,
    SignupView,
    SuperviseurDashboardView,
    StageaireCoursDetailView,
    StageaireCoursFichierDownloadView,
    StageaireControleFichierDownloadView,
    StageaireSubmitControleView,
    StageaireDashboardView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("references/", PublicReferenceDataView.as_view(), name="references-public"),
    path("me/", MeView.as_view(), name="me"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("dashboard/instructeur/", InstructeurDashboardView.as_view(), name="dashboard-instructeur"),
    path("dashboard/stageaire/", StageaireDashboardView.as_view(), name="dashboard-stageaire"),
    path("dashboard/superviseur/", SuperviseurDashboardView.as_view(), name="dashboard-superviseur"),
    path("dashboard/coordinateur/", CoordinateurDashboardView.as_view(), name="dashboard-coordinateur"),
    path("dashboard/admin/", AdminDashboardView.as_view(), name="dashboard-admin"),
    path("instructeur/cours/", InstructeurCoursCreateView.as_view(), name="instructeur-cours-create"),
    path("instructeur/cours/<str:cours_id>/fichier/", InstructeurCoursFichierView.as_view(), name="instructeur-cours-fichier"),
    path("instructeur/cours/<str:cours_id>/fichier/<str:fichier_id>/", InstructeurCoursFichierDownloadView.as_view(), name="instructeur-cours-fichier-download"),
    path("instructeur/controles/", InstructeurControleCreateView.as_view(), name="instructeur-controle-create"),
    path("instructeur/controles/<str:controle_id>/fichier/", InstructeurControleFichierView.as_view(), name="instructeur-controle-fichier"),
    path("instructeur/soumissions/<str:soumission_id>/fichier/", InstructeurSoumissionFichierView.as_view(), name="instructeur-soumission-fichier"),
    path(
        "instructeur/soumissions/<str:soumission_id>/evaluate/",
        InstructeurEvaluateSoumissionView.as_view(),
        name="instructeur-evaluate-soumission",
    ),
    path(
        "instructeur/controles/<str:controle_id>/publish-correction/",
        InstructeurPublishCorrectionView.as_view(),
        name="instructeur-publish-correction",
    ),
    path("stageaire/cours/<str:cours_id>/", StageaireCoursDetailView.as_view(), name="stageaire-cours-detail"),
    path("stageaire/cours/<str:cours_id>/fichier/<str:fichier_id>/", StageaireCoursFichierDownloadView.as_view(), name="stageaire-cours-fichier-download"),
    path("stageaire/controles/<str:controle_id>/fichier/", StageaireControleFichierDownloadView.as_view(), name="stageaire-controle-fichier-download"),
    path(
        "stageaire/controls/<str:controle_id>/submit/",
        StageaireSubmitControleView.as_view(),
        name="stageaire-submit-control",
    ),
    path(
        "admin/users/<int:user_id>/toggle-active/",
        AdminToggleUserStatusView.as_view(),
        name="admin-toggle-user-status",
    ),
    path("admin/accounts/create/", AdminCreateAccountView.as_view(), name="admin-create-account"),
    path("admin/accounts/bulk-csv/", AdminBulkCreateAccountsCsvView.as_view(), name="admin-bulk-create-accounts"),
    path("admin/events/", AdminEventsView.as_view(), name="admin-events"),
    path("admin/references/", AdminReferenceDataView.as_view(), name="admin-reference-data"),
    path("admin/references/corps/", AdminCorpsView.as_view(), name="admin-create-corps"),
    path("admin/references/corps/<str:corps_id>/", AdminCorpsView.as_view(), name="admin-update-corps"),
    path("admin/references/ranks/", AdminRanksView.as_view(), name="admin-create-rank"),
    path("admin/references/ranks/<str:rank_id>/", AdminRanksView.as_view(), name="admin-update-rank"),
    path("admin/references/specialities/", AdminSpecialitiesView.as_view(), name="admin-create-speciality"),
    path(
        "admin/references/specialities/<str:speciality_id>/",
        AdminSpecialitiesView.as_view(),
        name="admin-update-speciality",
    ),
    path("admin/classes/", AdminClassesView.as_view(), name="admin-classes"),
    path(
        "admin/classes/<str:class_id>/assign-stageaire/",
        AdminAssignStageaireToClassView.as_view(),
        name="admin-assign-stageaire-class",
    ),
    path(
        "admin/classes/<str:class_id>/assign-instructeur/",
        AdminAssignInstructeurToClassView.as_view(),
        name="admin-assign-instructeur-class",
    ),
    path("admin/subjects/", AdminSubjectsView.as_view(), name="admin-subjects"),
    path("admin/subjects/<str:subject_id>/controls/", AdminSubjectControlsView.as_view(), name="admin-subject-controls"),
    path("admin/subjects/<str:subject_id>/courses/", AdminSubjectCoursesView.as_view(), name="admin-subject-courses"),
    path("admin/controls/<str:controle_id>/status/", AdminUpdateControlStatusView.as_view(), name="admin-control-status"),
    path("admin/courses/<str:cours_id>/status/", AdminUpdateCourseStatusView.as_view(), name="admin-course-status"),
]
